version: "2"
services:

  db:
    container_name: reto1db
    image: reto1db
    networks: ["vnet"]
    ports:
      - 3306:3306
    expose:
      - 3306
    environment: 
      MYSQL_ROOT_PASSWORD: passwd

  coordinator-1:
    container_name: coordinator-1
    networks: ["vnet"]
    depends_on:
      - db
    links:
      - db:reto1db
    hostname: coordinator-1.vnet
    image: reto1prestodb
    ports: 
      - 8888:8888
    environment:
      - PRESTO_JVM_MAX_HEAP=512M
      - PRESTO_QUERY_MAX_MEMORY=1GB
      - PRESTO_QUERY_MAX_MEMORY_PER_NODE=256MB
      - TERM=xterm
      - PRESTO_DISCOVERY_PORT=8888
      - PRESTO_DISCOVERY_URI=http://coordinator-1.vnet:8888
    command: coordinator
      
networks:
  vnet:
    external:
      name: vnet 
