version: "2"
services:

  notebook:
    container_name: notebook
    image: zeppelin
    networks: ["vnet"]
    ports:
      - 8880:8880
    expose:
      - 8880
    environment: 
      ZEPPELIN_PORT: 8880
    external_links:
      - ${external_links_db}
      - ${external_links_presto}

networks:
  vnet:
    external:
      name: vnet
